// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUamso4IHuqhLpLhgFc8q6fJei4bSTl5I',
    appId: '1:618060458330:web:bcc210104750c32a5b6b63',
    messagingSenderId: '618060458330',
    projectId: 'nutra-675cd',
    authDomain: 'nutra-675cd.firebaseapp.com',
    storageBucket: 'nutra-675cd.firebasestorage.app',
    measurementId: 'G-YHQGLDX9P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiZOrqWxcBjdEY1aTLFLDlLCzyu0FrtwQ',
    appId: '1:618060458330:android:fa787b20e3d62e4f5b6b63',
    messagingSenderId: '618060458330',
    projectId: 'nutra-675cd',
    storageBucket: 'nutra-675cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNIqtu01SWl-eM-Pq_6zC_fBlsQEVSmvk',
    appId: '1:618060458330:ios:5b5c3d6d3c4307145b6b63',
    messagingSenderId: '618060458330',
    projectId: 'nutra-675cd',
    storageBucket: 'nutra-675cd.firebasestorage.app',
    iosBundleId: 'br.com.nutraentes.nutra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNIqtu01SWl-eM-Pq_6zC_fBlsQEVSmvk',
    appId: '1:618060458330:ios:9ed5802f7e6278c45b6b63',
    messagingSenderId: '618060458330',
    projectId: 'nutra-675cd',
    storageBucket: 'nutra-675cd.firebasestorage.app',
    iosBundleId: 'com.example.nutraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUamso4IHuqhLpLhgFc8q6fJei4bSTl5I',
    appId: '1:618060458330:web:d13bea311aeea8cc5b6b63',
    messagingSenderId: '618060458330',
    projectId: 'nutra-675cd',
    authDomain: 'nutra-675cd.firebaseapp.com',
    storageBucket: 'nutra-675cd.firebasestorage.app',
    measurementId: 'G-K6D479YNF8',
  );
}